config = {
	"shadow_min_hue": 300,
	"shadow_max_hue": 0,
	"shadow_min_saturation": 0,
	"shadow_max_saturation": 100,
	"shadow_min_intensity": 0,
	"shadow_max_intensity": 200,
	"light_min_hue": 180,
	"light_max_hue": 240,
	"light_min_saturation": 0,
	"light_max_saturation": 100,
	"light_min_intensity": 0,
	"light_max_intensity": 200,
	"line_min_hue": 0,
	"line_max_hue": 180,
	"line_min_saturation": 0,
	"line_max_saturation": 100,
	"line_min_intensity": 0,
	"line_max_intensity": 200
}